### ISSUE TITLE
Too many errors to list

### ISSUE THREAD

**Issue by ClosetGeek-Git** [LobbyOS/android-standalone#2]
This simply doesn't work and I'm doubting was even ever tested. For example, 'make clean' cannot be called without an error until make has been called at least once, yet mkdir cannot be called more than once without error. So it can't be ran without first commenting out 'make clean', then flowing builds will need mkdir commented out.

Not to mention libcrypt failed, as did libxml2, openssl, and PHP itself including after removing all extensions from configure line and adding '--disable-all' (see other issue regarding dns.c errors). Please fix bugs in code or change instructions to explain how to make it actually work.

**Comment by subins2000** [comment]
* I added `make clean` to the script, because I was recompiling over and over again
* In the latest commit, I have added `-p` to mkdir to prevent errors
