### ISSUE TITLE
Should SYSROOT var have trailing slash in setenv.sh?

### ISSUE THREAD

**Issue by ClosetGeek-Git** [LobbyOS/android-standalone#4]
[line 19](https://github.com/LobbyOS/android-standalone/blob/master/compile/setenv.sh#L19) in compile/setenv.sh

`SYSROOT="$PLATFORM/$ANDROID_ARCH/"`

This creates double slashes in 2 places in php7's Makefile

`-I${SYSROOT}/usr/include` comes out as `-I/foo/bar/android-16/arch-arm//usr/include` etc

**Comment by subins2000** [comment]
That won't affect compilation http://unix.stackexchange.com/a/11965
